codecov: true
language: java
jdk:
  - openjdk14

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -email
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="a17d7df0-2620-4650-80d5-8b176d4ca785"